spring:
  application:
    name: lodge
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/coupon
    driver-class-name: org.postgresql.Driver
    username: fouribnb
    password: 1234
  #    url:  jdbc:h2:mem:lodge;
  #    username: sa
  #    password:
  #    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
  h2:
    console:
      enabled: true
server:
  port: 19099




#  config:
#    import: "configserver:http://localhost:18080"

#server:
#  port: 0
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:19090/eureka/
#
#message: "default message" # config server? ???? ?? ?
#
#management:
#  endpoints:
#    web:
#      exposure:
#        include: refresh